### ISSUE TITLE
Problème avec l'administration

### ISSUE THREAD

**Issue by jimmyr57000** [Uneo7/WHMCS-Proxmox-Gateway#1]
Bonjour,

De mon côté l'administration ne fonctionne pas..

Cela me retourne: Erreur : Impossible de trouver l'action demandée
Monsite.fr/admin/addonmodules.php?module=proxmox_addon

Merci d'avance

**Comment by jimmyr57000** [comment]
Désolé je n'est pas vu que ce n'étais pas toi le créateur du Module.

**Comment by Uneo7** [comment]
Bonjour @jimmyr57000 Je suis le créateur du module, reagrde les commits :slightly_smiling_face: 
A ce propos, je serais bien curieux de savoir d'où tu sort cette info.

Peut tu m'en dire un peut plus sur ton problème ?

**Comment by jimmyr57000** [comment]
D’accord ^^

J’ai un message d’erreur quand j’essaie de me rendre sur l’administration du plugin..

La première erreur quand le plugin était bien actif l’espace administratif me retourner un message en rouge quelque chose comme action nous trouver

J’ai essayé de réactiver le plugin tous à l’heur sauf que:
Addon Module Activé
Impossible de créer la table : SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'mod_promox_addon_vms' already exists (SQL: create table `mod_promox_addon_vms` (`id` int unsigned not null auto_increment primary key, `vmid` varchar(255) not null, `service_id` int not null, `node_id` int not null) default character set utf8 collate utf8_unicode_ci)

**Comment by Uneo7** [comment]
L'erreur que tu as semble être due au fait que quand le module est désactivé, une table ne doit pas se supprimer correctement.

Pour régler ça je recommande de supprimer toutes les tables en `mod_promox_` puis réactiver le module.

Je tiens à te rappeler que ce module est une version de dev et pas ce que j'utilise en production, il y donc des bugs :slightly_smiling_face:.

Si tu veut proposer des fix, tu peut faire des pr je traiterais ça le plus rapidement possible.

**Comment by jimmyr57000** [comment]
Effectivement, j'ai reussi à réactiver le module.. 
J'arrive à nouveau à obtenir la première erreur:
https://monsite.r/admin/addonmodules.php?module=proxmox_addon
Me retourne: 

Promox Gateway
Erreur : Impossible de trouver l'action demandée

Pas de soucis pour les PR!

**Comment by Uneo7** [comment]
J'ai passé un premier fix pour corriger les tables qui ne supprimais pas correctement, pour le dispatcher qui t'affichais le message en rouge normalement c'est réglé aussi.

Je te laisse tester et me dire quoi :slightly_smiling_face:

**Comment by jimmyr57000** [comment]
Effectivement, c'est l'argement mieux ! 

Par-contre lors de la tentative de création de la VM: 
VM Creation failed with error : API responded with an unknown error.

**Comment by Uneo7** [comment]
Tout est dans le module log de WHMCS, faut que tu regarde ça doit certainement être un truc tout con en rapport avec l'api PVE.

**Comment by jimmyr57000** [comment]
Justement la réponse et plutôt épic ^^ 

Réponse: 
stdClass Object
(
    [data] => 
)

**Comment by Uneo7** [comment]
Haha un classique ce promox, il réponds juste ça marche pas, sans plus d'info, tu verra avec le temps tu va t'y faire ^^ 

Si tu me donne la query qui est passée je pourrais sans doute te dire ce qui ne va pas :slightly_smiling_face:

**Comment by jimmyr57000** [comment]
Voilà ^^
Merci à toi, c'est sympa de m'aider 👍 

Array
(
    [0] => PROXMOX
    [1] => Array
        (
            [vmid] => 108
            [onboot] => 
            [description] => Client: Jimmy Rich  (ID: 1)
Email: contact@jimmyrich.fr
Service ID: 2803
Product:  VPS S (ID: 59)
            [start] => 1
            [hostname] => monvps.fr
            [rootfs] => local:10
            [ostemplate] => local:vztmpl/ubuntu-19.10-standard_19.10-1_amd64.tar.gz
            [memory] => 2048
            [swap] => 1024
            [password] => !7#sH0JzYmz15X
            [cores] => 1
        )

)

**Comment by Uneo7** [comment]
Il manque la partie réseau mais de mémoire on peut créer on container sans, il faut verifier avec l'api proxmox ce qui est requis et si tout est bien formaté.

**Comment by jimmyr57000** [comment]
J'ai fait le tour de ma configuration, j'ai regarder au niveau du produit que j'ai créer..
Je n'avais pas selectionner l'interface que j'ai crée (Nom: eth0) 
Cette erreur et maintenant retourner par le module: 

VM Creation failed with error : Network creation failed

Edit: Je vais essayé de comprendre leur API.. je suis un peut 0 avec ça

**Comment by Uneo7** [comment]
Celle-ci ne viens pas de l'api, elle proviens d'une mauvaise configuration réseau dans le module.
Verifie dans la liste des tâches fails depuis l'accueil que tu n'as pas une erreur du genre : `No enough IPv4 adresses available in cluster `

**Comment by jimmyr57000** [comment]
Effectivement: No enough IPv4 adresses available in cluster : Craftaserv

Edit: L'ipv4 était en privé.. quelle débile ^^

**Comment by jimmyr57000** [comment]
Vachement propre ton module, par-contre dommage que la réinstallation de la VM ne fonctionne pas.. cela supprime la VM puis ne la crée pas (malgré la tache cron)

**Comment by Uneo7** [comment]
La réinstallation marche, mais il peut rester un bug ou deux, je t'invite à fouiller un peut dans les logs tu devrais trouver ce qui ne va pas assez rapidement.

Après sur la version que j'ai en prod, il est vrais que j'ai du retravailler quelques bug sur la réinstallation mais surtout pour recover après un fail.

**Comment by jimmyr57000** [comment]
Personnellement, je serais près à te payé la version que tu à en prod sans problème !
J'ai pas envi de trop bricoler le module pour y faire n'importe quoi..

**Comment by Uneo7** [comment]
C'est pas trop mon objectif et puis j'ai 0 disponibilitée pour l'upgrade ou faire du support dessus.
Ce module est là pour aider à ce lancer, mais sans faire du tout cuit :slightly_smiling_face:

**Comment by jimmyr57000** [comment]
Pas de soucis, merci à toi! 
J’ai finalement acheter le module le plus utilisé 
Bonne continuation encore désolé de t’avoir fait perdre du temps!

**Comment by Uneo7** [comment]
Haha le fameux de module garden, on l'as remplacé par ce que j'ai dev car il buggais de trop ^^
Et surtout on pouvais pas en faire ce qu'on voulais ce qui est très chiant quand tu as des besions spécifiques. Pour ça que je deteste le code fermé et WHMCS :smile:
