### ISSUE TITLE
VM Creation failed with error : API responded with an unknown error.

### ISSUE THREAD

**Issue by noysteque** [Uneo7/WHMCS-Proxmox-Gateway#2]
Salut !

Alors actuellement, j'ai un souci. Je tourne sous WHMCS 8.X.

Quand j'essaie de créer une CT via WHMCS j'ai cette erreur dans le titre, alors j'ai regardé un issue qui avais été fermé il y a 1 an, et j'ai check, et re-check tous mes paramètres, tout est configuré, je le pense correctement de mon côté. Que ce soit l'interface réseau, jusqu'aux IPs.

Le module fait bien une tentative de création, mais arrive a un échec, comme on peut le voir sur ce screen là. (et comme d'habitude Proxmox ne donne aucune information du pourquoi du comment).

![Capture](https://user-images.githubusercontent.com/21891714/115118556-add38580-9f9b-11eb-96ea-683f96f66b67.PNG)

Je te remercie d'avance.

**Comment by Uneo7** [comment]
Salut,

Premièrement, je ne l'ai jamais testé pour WHMCS 8, je ne sais pas du tout si tout va marcher comme prévu.

De plus, ce module est là comme base de travail et n'est pas prévu tel quel pour la production.

La version que j'utilise en production a subis de nombreux patchs et modification pour être fin prête.

Mon objectif ici, n'est pas de pondre un truc tout cuit et d'alimenter par la même occasion, cet espèce de course inaliénable à la création d'hébergeurs bercés par des idéaux de rentabilités totalement illusoires. Aussi, afin d'utiliser ce module il va te falloir comprendre le fonctionnement de proxmox, de whmcs ainsi que de t'intéresser à la programmation ; en conclusion t'intéresser à l’hébergement un peut plus qu'installer whmcs et des modules.

Ce module est gratuit certes mais il viens au prix du temps que tu va devoir y consacrer (ce qui in finé est je trouve bien plus gratifiant).

Quant au problème en lui-même, je ne vois rien de transcendant, mais si je puis te faire une recommandation c'est d'essayer dumper la réponse complète des request dans la cron. De cette manière, tu pourra obtenir plus d'informations pas forcément affichées de prime abord qui t'aiderons j'en suis certain à régler ton problème.

Bien à toi,
Uneo
